name: Docs Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Protobuf & NanoPB
      run: |
        sudo apt-get -y install protobuf-compiler protobuf-c-compiler
        sudo apt-get -y install python3-pip
        pip3 install nanopb        
        wget https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.5.0/protoc-gen-doc-1.5.0.linux-amd64.go1.16.6.tar.gz
        tar -xvf protoc-gen-doc-1.5.0.linux-amd64.go1.16.6.tar.gz
        sudo cp protoc-gen-doc-1.5.0.linux-amd64.go1.16.6/protoc-gen-doc /usr/bin/
        rm -rf protoc-gen-doc-1.5.0.linux-amd64.go1.16.6*
    - name: Generate
      run: |
        mkdir python
        mkdir c
        mkdir cpp
        mkdir nanopb
        mkdir docs
        ./generate.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs